# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#hero"
  weight = 10

[[main]]
  name = "Publications"
  url = "#publications"
  weight = 20

[[main]]
  name = "Presentations"
  url = "#talks"
  weight = 30

[[main]]
  name = "Honors"
  url = "#accomplishments"
  weight = 40

[[main]]
  name = "Skills"
  url = "#skills"
  weight = 50

[[main]]
  name = "Posts"
  url = "#posts"
  weight = 60

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 70

[[main]]
  name = "CV"
  url = "files/cv.html"
  weight = 80

